name: Build
on: [push]

jobs:
  linux:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    env:
      build_conan_path: "$HOME/.local/bin"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Install conan
        shell: bash
        run: |
          pip3 install wheel setuptools
          pip3 install conan

      - if: matrix.os == 'macOS-latest'
        name: install clang-format
        run: |
          brew install clang-format

      - name: configure
        shell: bash
        run: |
          export PATH="${{ env.build_conan_path }}":$PATH
          mkdir build && cd build
          conan profile new cxx11 --detect
          if [ "$RUNNER_OS" == "Linux" ]; then
             conan profile update settings.compiler.libcxx=libstdc++11 cxx11
          fi
          conan install .. --profile cxx11
          cmake ../
      - name: build
        run: cd build && cmake --build ./

        
