name: Build
on: [push]

jobs:
  linux:
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Install conan
        shell: bash
        run: pip3 install conan

      - name: configure
        run: |
          mkdir build && cd build
          conan install ..
          cmake ../
      - name: build
        run: cd _build && cmake --build ./

        