name: Build
on: [push]

jobs:
  linux:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    env:
      build_conan_path: "$HOME/.local/bin"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Install conan
        shell: bash
        run: |
          pip3 install wheel setuptools
          pip3 install conan

      - name: configure
        shell: bash
        run: |
          export PATH="${{ env.build_conan_path }}":$PATH
          mkdir build && cd build
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan install ..
          cmake ../
      - name: build
        run: cd build && cmake --build ./

        