name: Build
on: [push]

jobs:
  linux:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    env:
      build_conan_path: "$HOME/.local/bin"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Conan Environment
        uses: hankhsu1996/setup-conan@v1.1.0

      - if: matrix.os == 'macOS-latest'
        name: install clang-format
        run: |
          brew install clang-format

      - name: configure
        shell: bash
        run: |
          export PATH="${{ env.build_conan_path }}":$PATH
          mkdir _build && cd _build
          conan profile detect --name cxx11
          conan install .. -pr:a cxx11 -s build_type=Release -s compiler.cppstd=17 --build=missing --output-folder=.
          cmake .. -DCMAKE_TOOLCHAIN_FILE="./conan_toolchain.cmake" -DCMAKE_BUILD_TYPE=Release
      - name: build
        run: cd build && cmake --build ./

        
