name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: mkdir _build && cd _build && cmake ../ -DENABLE_CXX17=OFF
    - name: build
      run: cd _build && cmake --build ./